source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'rails', '~> 3.1.0'
gem 'mm-versionable', '0.2.5'
gem 'noodall-ui', '~> 0.5.0'
gem 'noodall-devise'
gem 'bson_ext'
gem 'dragonfly'
gem 'rack-contrib', :require => 'rack/contrib'

group :production, :staging do
  gem 'dalli'
end

<%= assets_gemfile_entry %>
<%= javascript_gemfile_entry %>

group :development, :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'rspec-rails'
  gem 'launchy'    # So you can do Then show me the page
  gem 'factory_girl_rails'
  gem 'fakerama'
end
