source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'noodall-ui'
gem 'noodall-devise'
gem 'bson_ext', '~> 1.0.9'
gem 'rmagick', :require => 'RMagick'
gem 'dragonfly', '~> 0.7.6'


group :development, :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'rspec-rails', "~> 2.0.0.beta.22"
  gem 'spork'
  gem 'launchy'    # So you can do Then show me the page
  gem 'jeweler', '~> 1.4.0'
  gem 'factory_girl_rails'
  gem "faker", "~> 0.3.1"
  gem "haml"
end
