source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'rails', '> 3.0'
gem 'noodall-ui'
gem 'noodall-devise'
gem 'bson_ext'
gem 'dragonfly'
gem 'rack-contrib', :require => 'rack/contrib'

group :production, :staging do
  gem 'dalli'
  gem 'rack-cache', '~> 1.0.0', :require => 'rack/cache'
end

group :development, :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'rspec-rails'
  gem 'spork'
  gem 'launchy'    # So you can do Then show me the page
  gem 'factory_girl_rails'
  gem 'fakerama'
end

